### ISSUE TITLE
Memory exhausted in Technical Debt (Stage: Test)

### ISSUE THREAD

**Issue by vinpel** [php-censor/php-censor#82]
got this error :
```shell
RUNNING PLUGIN: Technical Debt (Stage: Test)
ErrorException: 1: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 2137320387 bytes) in /data/htdocs/phpci/src/PHPCensor/Plugin/TechnicalDebt.php line 174 (uncaught exception) at /data/htdocs/phpci/src/PHPCensor/Plugin/TechnicalDebt.php line 174
Can`t build - status is not pending
```

**Comment by corpsee** [comment]
Thanks @vinpel! There is a non-optimal code with `file_get_contents` of the all content of file in TechnicalDebt plugin. And it is a problem for big files.

P.S.: temporary solutions:
* Increase `memory_limit` `php.ini` parameter;
* Ignore directory with very big files;

**Comment by corpsee** [comment]
@vinpel I improved Technical Debt parsing. Can you check your problem in `feature-technical-debt-fix` branch?

**Comment by vinpel** [comment]
i have allowed more memory to php-censor so i don't get any error.
I've switch to you'r branch.


Somes projet doesn't find any FIXME ... but i'm sure i've somes

```
RUNNING PLUGIN: Technical Debt (Stage: Test)
Found 0 instances of TODO, FIXME, TO DO, FIX ME
PLUGIN: SUCCESS
```

FYI the documentation speak of technitial dep**P**t, probably a typo

**Comment by corpsee** [comment]
@vinpel Thank you for typo and testing! :+1: I fixed typo error in the docs and FIXME too. Can you check again?

P.S.: Old Technical Debt plugin also had bug: we see only first type of debt (TODO, FIXME and etc.) on one file. This bug fixed too.

**Comment by vinpel** [comment]
Still the same problem.

When i start in debug mode no commande information ? :
```
RUNNING PLUGIN: PHP Docblock Checker (Stage: Test)
Plugin options: {"skip-signatures":true,"allow_failures":true}
Looking for binary: phpdoccheck
Found in ./vendor/bin (local): phpdoccheck
Args: ["\/data\/htdocs\/phpcensor\/runtime\/builds\/1736_c94a0\/vendor\/bin\/phpdoccheck --json --directory=\"%s\"%s%s","\/data\/htdocs\/phpcensor\/runtime\/builds\/1736_c94a0\/"," --exclude=\"vendor,tests\/_support\/_generated,web\/assets,runtime\/,modules\/service\/tests\/_support,modules\/historique\/tests\/_support,modules\/ordonnateur\/tests\/_support\"",""]
Command: ./vendor/bin/phpdoccheck --json --directory="./" --exclude="vendor,tests/_support/_generated,web/assets,runtime/,modules/service/tests/_support,modules/historique/tests/_support,modules/ordonnateur/tests/_support"
Execution status: 1
PLUGIN: FAILED (ALLOWED)

RUNNING PLUGIN: Technical Debt (Stage: Test)
Plugin options: {"allow_failures":true}
Found 0 instances of TODO, FIXME, TO DO, FIX ME
PLUGIN: SUCCESS

RUNNING PLUGIN: SensioLabs Security Checker (Stage: Test)
```

**Comment by corpsee** [comment]
@vinpel Were you restart worker? I tested locally and `FIXME` (and other) worked...

**Comment by corpsee** [comment]
@vinpel Finally fixed, I hope... :smile:

**Comment by vinpel** [comment]
still no info.

I have used  this .php-censor.yml file to simplify the process :
```yaml
build_settings:
    verbose:                true
    prefer_symlink:         false
    allowed_warnings:       2
    ignore:
      - vendor
      - web/assets
      - runtime/
      - tests/_support/_generated
       # CRUD files with duplicates
      - controllers/configuration
    mysql:
      host:                 "127.0.0.1"
      user:                 "root"
      pass:                 "************"
setup:
  mysql:
    - "DROP DATABASE IF EXISTS TEST_DB_BUILD_%BUILD%;"
    - "CREATE DATABASE TEST_DB_BUILD_%BUILD%;"
    - "GRANT ALL PRIVILEGES ON test.* TO test@'localhost' IDENTIFIED BY 'test';"
  composer:
      directory:            "."
      action:               "install"
      prefer_dist:          true
  shell:
#
# Modification de la configuration pour être sur d'avoir une base de donnée vierge
    - "echo TEST_DB_BUILD_%BUILD%"
    - "sed -i -e 's,yii2_basic_tests,TEST_DB_BUILD_%BUILD%,g' %BUILD_PATH%config/db_test.php"
# Pour la connection à une base mySQL au lieu de Oracle
    - "sed -i -e 's,yii2_basic_tests,TEST_DB_BUILD_%BUILD%,g' %BUILD_PATH%config/db_oracle.php"
# Pour le Dump qui simule les données d'Oracle
    - "sed -i -e 's,yii2_basic_tests,TEST_DB_BUILD_%BUILD%,g' %BUILD_PATH%codeception.yml"

    - "%BUILD_PATH%vendor/bin/codecept build"
test:
  technical_debt:
    allow_failures:         true
complete:
  mysql:
    - "DROP DATABASE TEST_DB_BUILD_%BUILD%;"
  email:
    default_mailto_address: ***@***.fr
```
a search in file in the project :

![image](https://user-images.githubusercontent.com/1699839/33772333-8d45437c-dc34-11e7-9c33-b3a86758a262.png)

**Comment by corpsee** [comment]
It is very strange... I test [this project](https://github.com/php-censor/php-censor-test/blob/master/src/Application.php) and see:

```
RUNNING PLUGIN: Technical Debt (Stage: Test)
Plugin options: {"allow_failures":true}
Found 3 instances of TODO, FIXME, TO DO, FIX ME
PLUGIN: FAILED (ALLOWED)
```

Code:
```php
<?php

namespace PHPCensorTest;

class Application
{
    public function success()
    {
        // TODO: 1
        echo 'success command';
        exit(0);
    }

    public function failed()
    {
        // TODO: 2
        echo 'failed command';
        // FIXME: 3
        exit(1);
    }
}
```

**Comment by corpsee** [comment]
@vinpel Are you using MySQL for main PHP Censor DB? May be it is problem... I will test MySQL today.

**Comment by corpsee** [comment]
And what PHP version?

**Comment by corpsee** [comment]
I checked again on MySQL and PHP 7.1 and 7.2. Everything is correct. :confused: I will not close and merge yet...

**Comment by vinpel** [comment]
sorry i don't work during the week-end.

I use : 
```
PHP 7.1.5 (cli) (built: May 13 2017 10:49:18) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
```

mariaDb : 
```
registry-1.docker.io/library/mariadb:latest
```

The debug launch didn't display the command, it's  a call of a class directly, how can i test to maybe see a clear error message ?

**Comment by corpsee** [comment]
Something should be in the log `runtime/console.log`...

**Comment by vinpel** [comment]
No command seem to be launched :
```
[2017-12-12 07:12:57] php-censor.INFO:  RUNNING PLUGIN: PHP Docblock Checker (Stage: Test) {"build":"[object] (PHPCensor\\Model\\Build\\GogsBuild: {\"currentBuildPath\":\"/data/htdocs/phpcensor/runtime/builds/1746_7e3bf/\"})"} []
[2017-12-12 07:12:57] php-censor.INFO: Plugin options: {"skip-signatures":true,"allow_failures":true} {"build":"[object] (PHPCensor\\Model\\Build\\GogsBuild: {\"currentBuildPath\":\"/data/htdocs/phpcensor/runtime/builds/1746_7e3bf/\"})"} []
[2017-12-12 07:12:57] php-censor.INFO: Looking for binary: phpdoccheck {"build":"[object] (PHPCensor\\Model\\Build\\GogsBuild: {\"currentBuildPath\":\"/data/htdocs/phpcensor/runtime/builds/1746_7e3bf/\"})"} []
[2017-12-12 07:12:57] php-censor.INFO: Found in /data/htdocs/phpcensor/runtime/builds/1746_7e3bf/vendor/bin (local): phpdoccheck {"build":"[object] (PHPCensor\\Model\\Build\\GogsBuild: {\"currentBuildPath\":\"/data/htdocs/phpcensor/runtime/builds/1746_7e3bf/\"})"} []
[2017-12-12 07:12:57] php-censor.INFO: Args: ["\/data\/htdocs\/phpcensor\/runtime\/builds\/1746_7e3bf\/vendor\/bin\/phpdoccheck --json --directory=\"%s\"%s%s","\/data\/htdocs\/phpcensor\/runtime\/builds\/1746_7e3bf\/"," --exclude=\"vendor,tests\/_support\/_generated,web\/assets,runtime\/,modules\/service\/tests\/_support,modules\/historique\/tests\/_support,modules\/ordonnateur\/tests\/_support\"",""] {"build":"[object] (PHPCensor\\Model\\Build\\GogsBuild: {\"currentBuildPath\":\"/data/htdocs/phpcensor/runtime/builds/1746_7e3bf/\"})"} []
[2017-12-12 07:12:57] php-censor.INFO: Command: /data/htdocs/phpcensor/runtime/builds/1746_7e3bf/vendor/bin/phpdoccheck --json --directory="/data/htdocs/phpcensor/runtime/builds/1746_7e3bf/" --exclude="vendor,tests/_support/_generated,web/assets,runtime/,modules/service/tests/_support,modules/historique/tests/_support,modules/ordonnateur/tests/_support" {"build":"[object] (PHPCensor\\Model\\Build\\GogsBuild: {\"currentBuildPath\":\"/data/htdocs/phpcensor/runtime/builds/1746_7e3bf/\"})"} []
[2017-12-12 07:13:00] php-censor.INFO: Execution status: 1 {"build":"[object] (PHPCensor\\Model\\Build\\GogsBuild: {\"currentBuildPath\":\"/data/htdocs/phpcensor/runtime/builds/1746_7e3bf/\"})"} []
[2017-12-12 07:13:00] php-censor.ERROR: PLUGIN: FAILED (ALLOWED) {"build":"[object] (PHPCensor\\Model\\Build\\GogsBuild: {\"currentBuildPath\":\"/data/htdocs/phpcensor/runtime/builds/1746_7e3bf/\"})"} []
[2017-12-12 07:13:00] php-censor.INFO:  RUNNING PLUGIN: Technical Debt (Stage: Test) {"build":"[object] (PHPCensor\\Model\\Build\\GogsBuild: {\"currentBuildPath\":\"/data/htdocs/phpcensor/runtime/builds/1746_7e3bf/\"})"} []
[2017-12-12 07:13:00] php-censor.INFO: Plugin options: {"allow_failures":true} {"build":"[object] (PHPCensor\\Model\\Build\\GogsBuild: {\"currentBuildPath\":\"/data/htdocs/phpcensor/runtime/builds/1746_7e3bf/\"})"} []
[2017-12-12 07:13:04] php-censor.INFO: Found 0 instances of TODO, FIXME, TO DO, FIX ME {"build":"[object] (PHPCensor\\Model\\Build\\GogsBuild: {\"currentBuildPath\":\"/data/htdocs/phpcensor/runtime/builds/1746_7e3bf/\"})"} []
[2017-12-12 07:13:04] php-censor.INFO: PLUGIN: SUCCESS {"build":"[object] (PHPCensor\\Model\\Build\\GogsBuild: {\"currentBuildPath\":\"/data/htdocs/phpcensor/runtime/builds/1746_7e3bf/\"})"} []
[2017-12-12 07:13:04] php-censor.INFO:  RUNNING PLUGIN: SensioLabs Security Checker (Stage: Test) {"build":"[object] (PHPCensor\\Model\\Build\\GogsBuild: {\"currentBuildPath\":\"/data/htdocs/phpcensor/runtime/builds/1746_7e3bf/\"})"} []
[2017-12-12 07:13:04] php-censor.INFO: Plugin options: {"allowed_warnings":-1} {"build":"[object] (PHPCensor\\Model\\Build\\GogsBuild: {\"currentBuildPath\":\"/data/htdocs/phpcensor/runtime/builds/1746_7e3bf/\"})"} []
[2017-12-12 07:13:09] php-censor.ERROR: Exception: An error occurred: Couldn't resolve host 'security.sensiolabs.org'. {"exception":"[object] (SensioLabs\\Securit
```

the build :
![image](https://user-images.githubusercontent.com/1699839/33871971-1dbc7208-df15-11e7-980c-325fca26af57.png)

**Comment by vinpel** [comment]
something is strange ... how did php-censor get his exclude liste ? (ignore).

Here is my full .php-censor.yml file :

```yml
build_settings:
    verbose:                true
    prefer_symlink:         false
    allowed_warnings:       2
    ignore:
      - vendor
      - web/assets
      - runtime/
      - tests/_support/_generated
       # CRUD files with duplicates
      - controllers/configuration
    mysql:
      host:                 "127.0.0.1"
      user:                 "root"
      pass:                 "*******"
setup:
  mysql:
    - "DROP DATABASE IF EXISTS TEST_DB_BUILD_%BUILD%;"
    - "CREATE DATABASE TEST_DB_BUILD_%BUILD%;"
    - "GRANT ALL PRIVILEGES ON test.* TO test@'localhost' IDENTIFIED BY 'test';"
  composer:
      directory:            "."
      action:               "install"
      prefer_dist:          true
  shell:
#
    - "echo Ajout des autorisations"
    
# Modification de la configuration pour être sur d'avoir une base de donnée vierge
    - "echo TEST_DB_BUILD_%BUILD%"
    - "sed -i -e 's,yii2_basic_tests,TEST_DB_BUILD_%BUILD%,g' %BUILD_PATH%config/db_test.php"
# Pour la connection à une base mySQL au lieu de Oracle
    - "sed -i -e 's,yii2_basic_tests,TEST_DB_BUILD_%BUILD%,g' %BUILD_PATH%config/db_oracle.php"
# Pour le Dump qui simule les données d'Oracle
    - "sed -i -e 's,yii2_basic_tests,TEST_DB_BUILD_%BUILD%,g' %BUILD_PATH%codeception.yml"

# Deploiement de l'application
    - "echo ajout droit execution"
    - "chmod +x %BUILD_PATH%tests/bin/yii"
    - "chmod +x %BUILD_PATH%scripts_rkt/deploy.sh"
    - "echo Deploiement"
    - "%BUILD_PATH%scripts_rkt/deploy.sh tests/bin/yii"
    - "echo ajout Build de codeception"
    - "%BUILD_PATH%vendor/bin/codecept build"
test:
  codeception:
    config:                 codeception.yml
    allow_failures:         false
    args:                   " -v "
  php_cpd:
    allow_failures:         true
  php_loc:
    allow_failures:         true
  php_parallel_lint:
    allow_failures:         true
  php_mess_detector:
    allow_failures: true
  php_code_sniffer:
    standard: "PSR2"
  php_docblock_checker:
    skip-signatures:        true
    allow_failures:         true
  technical_debt:
    allow_failures:         true
  security_checker:
    allowed_warnings:       -1
complete:
  mysql:
    - "DROP DATABASE TEST_DB_BUILD_%BUILD%;"
  email:
    default_mailto_address: *******

```

Now look at the excluded path :

 * modules/service/tests/_support
 * modules/historique/tests/_support 
 * modules/ordonnateur/tests/_support


i have .php-censor.yml file but under vendor/enterprise/modulesXXXXX
how did php-censor find them ?

i checked project didn't have a yml file:
![image](https://user-images.githubusercontent.com/1699839/33872291-8d7a1d92-df16-11e7-8551-052df9b38298.png)

**Comment by vinpel** [comment]
something is strange ... how did php-censor get his exclude liste ? (ignore).

Here is my full .php-censor.yml file :

```yml
build_settings:
    verbose:                true
    prefer_symlink:         false
    allowed_warnings:       2
    ignore:
      - vendor
      - web/assets
      - runtime/
      - tests/_support/_generated
       # CRUD files with duplicates
      - controllers/configuration
    mysql:
      host:                 "127.0.0.1"
      user:                 "root"
      pass:                 "*******"
setup:
  mysql:
    - "DROP DATABASE IF EXISTS TEST_DB_BUILD_%BUILD%;"
    - "CREATE DATABASE TEST_DB_BUILD_%BUILD%;"
    - "GRANT ALL PRIVILEGES ON test.* TO test@'localhost' IDENTIFIED BY 'test';"
  composer:
      directory:            "."
      action:               "install"
      prefer_dist:          true
  shell:
#
    - "echo Ajout des autorisations"
    
# Modification de la configuration pour être sur d'avoir une base de donnée vierge
    - "echo TEST_DB_BUILD_%BUILD%"
    - "sed -i -e 's,yii2_basic_tests,TEST_DB_BUILD_%BUILD%,g' %BUILD_PATH%config/db_test.php"
# Pour la connection à une base mySQL au lieu de Oracle
    - "sed -i -e 's,yii2_basic_tests,TEST_DB_BUILD_%BUILD%,g' %BUILD_PATH%config/db_oracle.php"
# Pour le Dump qui simule les données d'Oracle
    - "sed -i -e 's,yii2_basic_tests,TEST_DB_BUILD_%BUILD%,g' %BUILD_PATH%codeception.yml"

# Deploiement de l'application
    - "echo ajout droit execution"
    - "chmod +x %BUILD_PATH%tests/bin/yii"
    - "chmod +x %BUILD_PATH%scripts_rkt/deploy.sh"
    - "echo Deploiement"
    - "%BUILD_PATH%scripts_rkt/deploy.sh tests/bin/yii"
    - "echo ajout Build de codeception"
    - "%BUILD_PATH%vendor/bin/codecept build"
test:
  codeception:
    config:                 codeception.yml
    allow_failures:         false
    args:                   " -v "
  php_cpd:
    allow_failures:         true
  php_loc:
    allow_failures:         true
  php_parallel_lint:
    allow_failures:         true
  php_mess_detector:
    allow_failures: true
  php_code_sniffer:
    standard: "PSR2"
  php_docblock_checker:
    skip-signatures:        true
    allow_failures:         true
  technical_debt:
    allow_failures:         true
  security_checker:
    allowed_warnings:       -1
complete:
  mysql:
    - "DROP DATABASE TEST_DB_BUILD_%BUILD%;"
  email:
    default_mailto_address: *******

```

Now look at the excluded path :

 * modules/service/tests/_support
 * modules/historique/tests/_support 
 * modules/ordonnateur/tests/_support


i have .php-censor.yml file but under vendor/enterprise/modulesXXXXX
how did php-censor find them ?

i checked project didn't have a yml file:
![image](https://user-images.githubusercontent.com/1699839/33872291-8d7a1d92-df16-11e7-8551-052df9b38298.png)

**Comment by corpsee** [comment]
@vinpel  I will be able to look sources about your question (exclude list) tonight.

**Comment by corpsee** [comment]
@vinpel Can you check branch again on your project? I rewrited plugin again including logical of excluding files.

**Comment by vinpel** [comment]
i found the bug, will make a PR

**Comment by corpsee** [comment]
@vinpel Excellent! :+1: Thank you!

**Comment by vinpel** [comment]
the anomalie is caused by my ignored path "runtime"
the plugin wrongly manage relative, absolute path.

For ignore path it MUST be searched relative, but found a root of path.
Absolute path must be used when reading content of the file. (FIXME ...)

For  exemple if i add after the line "if (false !== strpos($filePath, $ignore)) {"
```php
  $this->builder->logDebug(' $filePath: ='.$filePath.'] $ignore ='.$ignore."] return".
            "\nstrstr : ".strstr($filePath, $ignore).
            "\nstrpos : ".strpos($filePath, $ignore)."\n".
            ' ignored 2');
```
i wil get :
```
RUNNING PLUGIN: Technical Debt (Stage: Test)
Plugin options: {"allow_failures":true}
Ignored path: ["vendor","tests\/_support\/_generated","web\/assets","runtime\/","modules\/service\/tests\/_support","modules\/historique\/tests\/_support","modules\/ordonnateur\/tests\/_support"]

 $relativePath: =./scripts_rkt/init.sh] $ignore =runtime/] return
strstr : runtime/builds/1815_d29a4/scripts_rkt/init.sh
strpos : 19
 ignored 2
 $relativePath: =./scripts_rkt/deploy.sh] $ignore =runtime/] return
strstr : runtime/builds/1815_d29a4/scripts_rkt/deploy.sh
strpos : 19
 ignored 2
```

Full path is : /data/htdocs/phpc/runtime/builds/1815_d29a4/
the 19 result is the /data/htdocs/phpci path


I have a really strange behavior, when i print $filepath in log it's correctly relative.
BUT when i do a strstr why did i get a different result ?

I have try to fix it without success:


``` 

if (false !== strpos((string)$filePath, $ignore)) {
OR 
      $filePath     = $file->getRealPath();
      $relativePath = (string)$file->getPathname();
``` 

still can get to test the relative path.

**Comment by vinpel** [comment]
working file : https://github.com/vinpel/php-censor/blob/932c51b48a75e3ac5aa2a37f254144c74523caf6/src/PHPCensor/Plugin/TechnicalDebt.php

(sorry messed indentation)

**Comment by vinpel** [comment]
fixed the issue :
![image](https://user-images.githubusercontent.com/1699839/33989141-b58f6038-e0c6-11e7-8df5-114b2edb9069.png)

see pull request : https://github.com/php-censor/php-censor/pull/141

**Comment by corpsee** [comment]
Thank you for the detailed explanation! I merged your request and my edits in the `master` branch, can I close the issue?

**Comment by vinpel** [comment]
yes you can !
